ignorePaths:
  - go.mod
  - go.sum
  - .gitignore
  - cspell.config.yaml
version: "0.2"
language: en
words:
  - boumenot
  - coverprofile
  - creasty
  - deepcopy
  - enumer
  - gocover
  - gotest
  - gotestfmt
  - gotesttools
  - irongut
  - marocchino
  - println
  - shopspring
  - stretchr
  - strs
  - zauberhaus
